import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import assert from "node:assert/strict";

const root = path.resolve(import.meta.dirname, "..");
// Built from concatenated fragments, not one literal pattern string, so this banned-word list's
// own source text does not itself match what it bans (this file would otherwise always be the
// one unavoidable false-positive hit in the very check it defines).
const BANNED = new RegExp(["human" + "layer", "human layer", "\\bhl[_:-]", "Human" + "Layer"].join("|"), "i");

// Guards against any residual reference to the third-party product this plugin's design was
// researched from. package-lock.json is exempt (npm-generated, regenerated by `npm install`,
// never hand-edited) and binary/image assets can't be grepped as text.
test("no tracked file mentions the third-party product this plugin's design was researched from", () => {
  const files = execFileSync("git", ["ls-files"], { cwd: root, encoding: "utf8" })
    .split("\n")
    .filter(Boolean)
    .filter((file) => file !== "package-lock.json")
    .filter((file) => !/\.(png|jpg|jpeg|gif|ico|mp3|wav|woff2?|ttf)$/i.test(file));

  const offenders: string[] = [];
  for (const file of files) {
    const full = path.join(root, file);
    let content: string;
    try {
      content = fs.readFileSync(full, "utf8");
    } catch {
      continue;
    }
    if (BANNED.test(content)) offenders.push(file);
  }
  assert.deepEqual(offenders, []);
});
